### ISSUE TITLE
Python 3.6 Certificate issues

### ISSUE THREAD

**Issue by jgiambo** [nd1/pycon_2017#1]
Python 3.6 does not contain any trusted certificates by default.  

To install a list of certificate authorities on 3.6

/Applications/Python\ 3.6/Install\ Certificates.command

Answer found from: http://stackoverflow.com/questions/27835619/ssl-certificate-verify-failed-error

**Comment by will2041** [comment]
Added note in README with 9ba354ec92363baf27ecfe2a4bd0e0ea641b82e8

Thanks for the issue.
